"""audit_guard.py — Defensive guard against LLM-generated audit hallucinations.

This script verifies audit claims BEFORE any human acts on them. It
runs cheap, deterministic checks (grep, file existence, test runs) that
catch the most common LLM-hallucination patterns:

  - Claiming a file exists that doesn't (e.g., "v1.8.5" in pyproject)
  - Claiming code is missing when it exists (e.g., "0 assert_allclose")
  - Claiming tests fail when they pass
  - Reporting stale numbers (e.g., coverage %)
  - Misreading API signatures

Usage:
    python scripts/audit_guard.py                      # run all checks
    python scripts/audit_guard.py --check 1,3,5        # specific checks
    python scripts/audit_guard.py --update-baseline    # refresh expected state
    python scripts/audit_guard.py --json               # machine-readable output

Exit code: 0 = all claims hold; 1 = at least one claim failed verification.

Design principle
----------------
Audit reports generated by LLMs frequently contain confident-sounding
claims that turn out to be false on inspection ("hallucinated fixes").
We accept that LLMs are useful for *finding* potential issues, but
NEVER trust them to verify their own findings. This script enforces
"show me the evidence" before any change is committed.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable


PROJECT_ROOT = Path(__file__).resolve().parent.parent


@dataclass
class AuditCheck:
    """Single verifiable audit claim."""

    id: int
    title: str
    description: str
    run: Callable[[], "CheckResult"]


@dataclass
class CheckResult:
    """Outcome of verifying a single audit claim."""

    passed: bool
    actual: str
    expected: str
    evidence: list[str] = field(default_factory=list)


# ────────────────────────────────────────────────────────────────────
# Individual checks
# ────────────────────────────────────────────────────────────────────


def _grep_count(pattern: str, glob: str, root: Path = PROJECT_ROOT) -> tuple[int, list[str]]:
    """Count files matching pattern; return (count, list_of_paths)."""
    cmd = ["grep", "-rln", "--include", glob, "--exclude-dir=.git", pattern, str(root)]
    res = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    paths = [p for p in res.stdout.strip().split("\n") if p]
    # Exclude audit-workflow.md (documents the v1.8.5 hallucination example)
    paths = [p for p in paths if not p.endswith("audit-workflow.md")]
    return len(paths), paths


def check_1_pypi_package_exists() -> CheckResult:
    """Audit claim: 'PyPI package finai-research-workflow doesn't exist.'

    We verify by hitting PyPI's JSON API.
    """
    import urllib.request
    import urllib.error

    evidence = []
    try:
        for name in ["finai-research-workflow", "finai_research_workflow"]:
            try:
                urllib.request.urlopen(
                    f"https://pypi.org/pypi/{name}/json", timeout=5
                )
                evidence.append(f"  PyPI {name}: EXISTS")
                return CheckResult(
                    passed=False,
                    actual="exists",
                    expected="not exists",
                    evidence=evidence,
                )
            except urllib.error.HTTPError:
                evidence.append(f"  PyPI {name}: 404 (not found)")
            except Exception as e:
                evidence.append(f"  PyPI {name}: error {e}")
        return CheckResult(
            passed=True,
            actual="not found",
            expected="not found",
            evidence=evidence,
        )
    except Exception as e:
        return CheckResult(
            passed=False,
            actual=f"error: {e}",
            expected="verifiable",
            evidence=[str(e)],
        )


def check_2_version_consistency() -> CheckResult:
    """Audit claim: 'README says v1.8.5 but pyproject is 0.1.0.'

    We grep user-facing docs (README*, pyproject, setup.cfg, __init__.py)
    for version references and report counts. Internal docs are excluded
    because they may legitimately discuss version history.
    """
    files_to_check = ["README.md", "README_EN.md", "pyproject.toml", "setup.cfg", "setup.py"]
    v185_count = 0
    v185_paths = []
    for f in files_to_check:
        p = PROJECT_ROOT / f
        if not p.exists():
            continue
        cmd = ["grep", "-n", "v1\\.8\\.5", str(p)]
        res = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        lines = [m for m in res.stdout.strip().split("\n") if m]
        v185_count += len(lines)
        v185_paths.extend(f"{f}:{m.split(':', 1)[1]}" for m in lines)

    pyproject_version = "?"
    pyproject_path = PROJECT_ROOT / "pyproject.toml"
    if pyproject_path.exists():
        text = pyproject_path.read_text()
        m = re.search(r'^version\s*=\s*"([^"]+)"', text, re.MULTILINE)
        if m:
            pyproject_version = m.group(1)

    evidence = [
        f"  pyproject.toml version: {pyproject_version}",
        f"  'v1.8.5' in user-facing files: {v185_count}",
    ]
    if v185_paths:
        evidence.extend(f"    → {p}" for p in v185_paths[:5])

    if v185_count == 0:
        return CheckResult(
            passed=True,
            actual=f"0 v1.8.5 references, pyproject={pyproject_version}",
            expected="consistent",
            evidence=evidence,
        )
    return CheckResult(
        passed=False,
        actual=f"{v185_count} v1.8.5 references in user-facing files",
        expected="0 references",
        evidence=evidence,
    )


def check_3_numerical_tests_exist() -> CheckResult:
    """Audit claim: 'Tests lack numerical correctness — 0 assert_allclose.'

    We grep tests/ for assert_allclose calls.
    """
    cmd = ["grep", "-rn", "assert_allclose\\|assert_almost_equal", "tests/"]
    res = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    matches = [m for m in res.stdout.strip().split("\n") if m and not m.endswith(".pyc")]
    count = len(matches)
    evidence = [f"  assert_allclose/assert_almost_equal calls: {count}"]
    if matches:
        evidence.extend(f"    → {m}" for m in matches[:5])

    if count > 0:
        return CheckResult(
            passed=True,
            actual=f"{count} calls found",
            expected=">0 calls",
            evidence=evidence,
        )
    return CheckResult(
        passed=False,
        actual="0 calls",
        expected=">0 calls",
        evidence=evidence,
    )


def check_4_coverage_threshold() -> CheckResult:
    """Audit claim: 'CI sets fail_under=6 (~6%).'

    We grep ci.yml for the actual value.
    """
    ci_path = PROJECT_ROOT / ".github" / "workflows" / "ci.yml"
    if not ci_path.exists():
        return CheckResult(
            passed=False,
            actual="ci.yml missing",
            expected="ci.yml present",
            evidence=[],
        )
    text = ci_path.read_text()
    m = re.search(r"fail[-_]under=(\d+)", text)
    if not m:
        return CheckResult(
            passed=False,
            actual="no fail-under directive",
            expected="fail-under=N",
            evidence=[],
        )
    val = int(m.group(1))
    evidence = [f"  fail-under={val}"]
    return CheckResult(
        passed=val >= 10,
        actual=f"fail-under={val}",
        expected="≥10 (after audit fix)",
        evidence=evidence,
    )


def check_5_pypi_badges_redirected() -> CheckResult:
    """Audit claim: 'README has fake PyPI badges.'

    We grep README.md for pypi.org/project/finai links.
    """
    cmd = ["grep", "-n", "pypi.org/project/finai\\|pypi/v/finai\\|pypi/dm/finai", "README.md", "README_EN.md"]
    res = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    matches = [m for m in res.stdout.strip().split("\n") if m]
    evidence = [f"  fake PyPI badge lines: {len(matches)}"]
    if matches:
        evidence.extend(f"    → {m}" for m in matches[:5])
    if len(matches) == 0:
        return CheckResult(
            passed=True,
            actual="no fake PyPI badges",
            expected="0 fake badges",
            evidence=evidence,
        )
    return CheckResult(
        passed=False,
        actual=f"{len(matches)} fake PyPI badges",
        expected="0 fake badges",
        evidence=evidence,
    )


def check_6_numerical_tests_pass() -> CheckResult:
    """Audit claim: 'Existing tests don't catch numerical regressions.'

    We run tests/test_numerical_correctness.py and verify all pass.
    """
    test_file = PROJECT_ROOT / "tests" / "test_numerical_correctness.py"
    if not test_file.exists():
        return CheckResult(
            passed=False,
            actual="test file missing",
            expected="test_numerical_correctness.py exists",
            evidence=[],
        )
    cmd = [sys.executable, "-m", "pytest", str(test_file), "-q", "--tb=no"]
    res = subprocess.run(cmd, capture_output=True, text=True, timeout=180, cwd=PROJECT_ROOT)
    # Parse last line for "N passed"
    summary = ""
    for line in res.stdout.splitlines() + res.stderr.splitlines():
        if "passed" in line and ("in " in line or "s)" in line):
            summary = line.strip()
    evidence = [f"  pytest exit: {res.returncode}", f"  summary: {summary}"]
    if res.returncode == 0:
        return CheckResult(
            passed=True,
            actual=f"all pass",
            expected="all pass",
            evidence=evidence,
        )
    return CheckResult(
        passed=False,
        actual=f"exit={res.returncode}",
        expected="exit=0",
        evidence=evidence,
    )


def check_7_demo_output_exists() -> CheckResult:  # pragma: no cover
    """Audit claim: 'No demo PDFs in papers/'.

    Disabled 2026-06-28 by user decision:
    - User removed papers/demo_outputs/ in commit 0872901
      (用户观点："当前留存只有负面影响")
    - Check 7 conflicted with that decision
    - Kept function as no-op stub so other code that imports it doesn't break
    """
    return CheckResult(
        passed=True,
        actual="disabled (user decision 2026-06-28)",
        expected="N/A",
        evidence=[],
    )
    tex_files = list(demo_dir.glob("*.tex"))
    pdf_files = list(demo_dir.glob("*.pdf"))
    evidence = [f"  .tex files: {len(tex_files)}", f"  .pdf files: {len(pdf_files)}"]
    if tex_files or pdf_files:
        return CheckResult(
            passed=True,
            actual=f"{len(tex_files)} tex, {len(pdf_files)} pdf",
            expected="≥1 demo output",
            evidence=evidence,
        )
    return CheckResult(
        passed=False,
        actual="empty",
        expected="≥1 demo output",
        evidence=evidence,
    )


def check_8_validate_econometrics_exists() -> CheckResult:
    """Audit claim: 'No R/Stata cross-validation.'

    Verify scripts/validate_econometrics.py exists and supports Stata.
    """
    target = PROJECT_ROOT / "scripts" / "validate_econometrics.py"
    if not target.exists():
        return CheckResult(
            passed=False,
            actual="missing",
            expected="validate_econometrics.py exists",
            evidence=[],
        )
    text = target.read_text()
    text_lower = text.lower()
    has_stata = "stata" in text_lower and ("reghdfe" in text_lower or "validate_against_stata" in text_lower)
    has_r = "fixest" in text_lower or "rscript" in text_lower or "validate_against_r" in text_lower
    evidence = [
        f"  Stata validation: {'yes' if has_stata else 'no'}",
        f"  R validation: {'yes' if has_r else 'no'}",
    ]
    if has_stata or has_r:
        return CheckResult(
            passed=True,
            actual=f"Stata={has_stata}, R={has_r}",
            expected="≥1 cross-validation",
            evidence=evidence,
        )
    return CheckResult(
        passed=False,
        actual="neither",
        expected="≥1 cross-validation",
            evidence=evidence,
        )


def check_9_ssot_numbers_match_docs() -> CheckResult:
    """Verify that PROJECT_NUMBERS.json (SSOT) matches the actual state.

    This is the root-cause fix for repeated number-hallucination audits:
    numbers drift when maintained in 5+ docs independently. The SSOT
    (scripts/PROJECT_NUMBERS.json) is the single source of truth; docs must
    be updated from it via sync_numbers.py --apply, not manually.
    """
    ssot_path = PROJECT_ROOT / "scripts" / "PROJECT_NUMBERS.json"
    if not ssot_path.exists():
        return CheckResult(
            passed=False,
            actual="SSOT file missing",
            expected="scripts/PROJECT_NUMBERS.json exists",
            evidence=[],
        )
    import json as _json
    ssot = _json.loads(ssot_path.read_text())

    # Verify MCP directory count
    import subprocess as _sub
    res = _sub.run(
        ["sh", "-c", f"ls {PROJECT_ROOT}/mcp_servers/ | grep '^user_' | wc -l"],
        capture_output=True, text=True,
    )
    actual_mcp = int(res.stdout.strip())
    ssot_mcp = ssot["mcp"]["total_directories"]
    mcp_ok = actual_mcp == ssot_mcp

    # Verify stub servers have tools/
    stub_issues = []
    for stub_name in ssot["mcp"].get("stub_servers", []):
        tools_dir = PROJECT_ROOT / "mcp_servers" / stub_name / "tools"
        if not tools_dir.exists():
            stub_issues.append(f"  {stub_name}: no tools/ directory")
        elif not list(tools_dir.glob("*.json")):
            stub_issues.append(f"  {stub_name}: tools/ is empty")
    stub_ok = len(stub_issues) == 0

    evidence = [
        f"  SSOT MCP directories: {ssot_mcp}, actual: {actual_mcp} → {'OK' if mcp_ok else 'MISMATCH'}",
        f"  SSOT stubs: {len(ssot['mcp'].get('stub_servers', []))}, actual stub issues: {len(stub_issues)}",
    ]
    if stub_issues:
        evidence.extend(stub_issues[:5])

    all_ok = mcp_ok and stub_ok
    return CheckResult(
        passed=all_ok,
        actual=f"MCP match={mcp_ok}, stubs={len(stub_issues)} issues",
        expected="SSOT matches actual state",
        evidence=evidence,
    )


def check_11_omit_longtail_not_growing() -> CheckResult:
    """Audit claim (audit-2026-07-04 P0-1): 'CI 覆盖率凑数通过新增 omit 藏分母'.

    Defense: bound the size of [tool.coverage.run] omit list. If it
    grows beyond a known set of legitimate CLI / DEPRECATED modules,
    this is a hallucinated-fix attempt and must be rejected.
    """
    p = PROJECT_ROOT / "pyproject.toml"
    if not p.exists():
        return CheckResult(False, "pyproject.toml missing", "exists", [])
    text = p.read_text()
    block_start = text.find("[tool.coverage.run]")
    if block_start < 0:
        return CheckResult(False, "no [tool.coverage.run] block", "present", [])
    rest = text[block_start:]
    # Stop at next TOML section header (line starting with `[name]`).
    block_lines = []
    lines = rest.splitlines(keepends=True)
    for idx, ln in enumerate(lines):
        if idx == 0:
            block_lines.append(ln)
            continue
        s = ln.strip()
        if s.startswith("[") and s.endswith("]") and not s.startswith("#"):
            break
        block_lines.append(ln)
    block = "".join(block_lines)
    in_omit = False
    omit_lines = []
    for ln in block.splitlines():
        s = ln.strip()
        if s.startswith("omit"):
            in_omit = True
            continue
        if in_omit:
            if s.startswith("]"):
                in_omit = False
                continue
            if s.startswith('"') and ".py" in s:
                omit_lines.append(s)
    count = len(omit_lines)
    # 2026-07-04 baseline (post PR-1): ~24 CLI/DEPRECATED entries.
    # Cap at 29 to allow legitimate additions; bigger is suspicious.
    cap = 29
    evidence = [f"  omit entries: {count}", f"  cap: {cap}"]
    if omit_lines:
        evidence.extend(f"    -> {x[:60]}" for x in omit_lines[:3])
    return CheckResult(
        passed=count <= cap,
        actual=f"{count} entries",
        expected=f"<= {cap}",
        evidence=evidence,
    )


def check_12_fail_under_floor() -> CheckResult:
    """Audit claim (audit-2026-07-04 P0-1): 'fail-under is repeatedly lowered
    (6 -> 3 -> 15 -> 25)'.

    Defense: enforce a minimum floor on fail-under. The floor is
    intentionally conservative (=25) at PR-1 time because removing the
    9 "CI not-imported" omit entries drops the apparent coverage from
    a padded 25-30% to a real 26-27%. PR-6 will add ~425 real tests to
    push coverage naturally above 30%, at which point this check's
    floor should be raised in lockstep.

    Audit guard against silent threshold drift downward.
    """
    ci = PROJECT_ROOT / ".github" / "workflows" / "ci.yml"
    if not ci.exists():
        return CheckResult(False, "ci.yml missing", "present", [])
    text = ci.read_text()
    import re
    matches = re.findall(r"fail[-_]under=(\d+)", text)
    if not matches:
        return CheckResult(False, "no fail-under directive", ">=25", [])
    vals = [int(x) for x in matches]
    min_v = min(vals)
    evidence = [
        f"  fail-under values found: {vals}",
        f"  minimum: {min_v}",
        f"  audit-2026-07-04 floor: 25 (PR-1); raise to 30 after PR-6",
    ]
    if min_v >= 25:
        return CheckResult(
            passed=True,
            actual=f"min={min_v}",
            expected=">=25 (audit-2026-07-04 floor at PR-1)",
            evidence=evidence,
        )
    return CheckResult(
        passed=False,
        actual=f"min={min_v}",
        expected=">=25",
        evidence=evidence,
    )


def check_13_workflow_yaml_unquoted_colons() -> CheckResult:
    """Verify all GitHub workflow YAML files parse, and warns on quoted-on-need
    patterns.

    Defense: dynamically parse every .yml/.yaml under .github/workflows/ with
    PyYAML, and additionally scan for the pattern 'name: <unquoted text with
    colon>' as a heuristic to catch the bug class even when other YAML in the
    file happens to parse (e.g. unquoted colons inside a `run:` block).
    """
    evidence: list[str] = []
    bad_files: list[str] = []

    for p in sorted((PROJECT_ROOT / ".github").rglob("*.y*ml")):
        rel = p.relative_to(PROJECT_ROOT)
        evidence.append(f"  parsing: {rel}")
        try:
            import yaml  # type: ignore[import-untyped]

            yaml.safe_load(p.read_text(encoding="utf-8"))
        except Exception as e:
            bad_files.append(f"{rel}: {type(e).__name__}: {e}")
        # Heuristic: scan for unquoted `name:` containing a colon.
        for i, line in enumerate(p.read_text(encoding="utf-8").splitlines(), 1):
            stripped = line.lstrip()
            if not stripped.startswith("- name:") and not stripped.startswith("name:"):
                continue
            # Extract value after `name:`.
            val = stripped.split("name:", 1)[1].lstrip()
            # If the value is unquoted and contains a colon, that's the bug.
            if val and not val.startswith('"') and not val.startswith("'"):
                if ":" in val:
                    bad_files.append(
                        f"{rel}:{i}: name field contains unquoted colon: {line.strip()!r}"
                    )

    if bad_files:
        return CheckResult(
            passed=False,
            actual=f"{len(bad_files)} issue(s)",
            expected="0 (every workflow YAML must parse; no unquoted `name:` colons)",
            evidence=evidence + [f"  PROBLEM: {x}" for x in bad_files],
        )
    return CheckResult(
        passed=True,
        actual="0 issues",
        expected="0",
        evidence=evidence,
    )


def check_14_diff_in_diff2_phantom_dep() -> CheckResult:
    """`diff-in-diff2` does not exist on PyPI as of 2026-07-04.

    PR-4's test-full job discovered this when `pip install -r requirements.txt`
    failed with `ERROR: Could not find a version that satisfies the requirement
    diff-in-diff2>=1.0.0`. The package was referenced in:
      * requirements.txt line 91
      * pyproject.toml [project.optional-dependencies.econometrics]
      * multiple docs (CLAUDE.md, README*.md)
      * scripts/research_framework/modern_did.py via `import diff_in_diff2`

    Defense: verify no active (uncommented) reference to `diff-in-diff2` or
    `diff_in_diff2` exists in requirements.txt, pyproject.toml, or any
    tracked source file. Commented-out lines are allowed (they document the
    historic decision).

    If anyone re-adds this dep without verifying PyPI existence, this check
    will fail and the related PR will not pass CI.
    """
    refs: list[str] = []
    pyproject = PROJECT_ROOT / "pyproject.toml"
    req = PROJECT_ROOT / "requirements.txt"

    for f in [pyproject, req]:
        if not f.exists():
            continue
        for i, line in enumerate(f.read_text(encoding="utf-8").splitlines(), 1):
            stripped = line.strip()
            if stripped.startswith("#"):
                continue
            if "diff-in-diff2" in line or "diff_in_diff2" in line:
                refs.append(f"active install: {f.relative_to(PROJECT_ROOT)}:{i}: {stripped}")

    # In source code, `import diff_in_diff2` is ALLOWED (graceful fallback
    # via EstimatorUnavailableError in scripts/research_framework/modern_did.py).
    # We only flag install directives in requirements files here.

    if refs:
        return CheckResult(
            passed=False,
            actual=f"{len(refs)} active install reference(s)",
            expected="0 (phantom dep — commented references or error-message strings only)",
            evidence=[f"  PROBLEM: {x}" for x in refs],
        )
    return CheckResult(
        passed=True,
        actual="0 active install references",
        expected="0",
        evidence=[
            "  verified: requirements.txt comment only",
            "  pyproject.toml comment only",
            "  runtime imports allowed (graceful EstimatorUnavailableError)",
        ],
    )


def check_15_pypi_deps_exist() -> CheckResult:
    """Spot-check every pip-installable dep declared in requirements.txt and
    pyproject.toml actually exists on PyPI.

    audit-2026-07-04 PR-4 caught `diff-in-diff2` (which doesn't exist) this
    way. Generalizing: for each non-comment line containing a `>=` or `==`
    pin, verify PyPI has at least one matching version. This is run on demand
    (not in CI by default) because PyPI is rate-limited, but it's a powerful
    audit signal.

    Skipped when network is unavailable.
    """
    import urllib.error
    import urllib.request

    deps: list[tuple[Path, int, str]] = []  # (file, line, dep_spec)
    for f in [PROJECT_ROOT / "pyproject.toml", PROJECT_ROOT / "requirements.txt"]:
        if not f.exists():
            continue
        for i, line in enumerate(f.read_text(encoding="utf-8").splitlines(), 1):
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            for tok in stripped.replace(" ", ",").split(","):
                tok = tok.strip().strip('"').strip("'")
                if ">=" in tok and not tok.startswith("-"):
                    deps.append((f, i, tok))
                    break
            else:
                continue

    # Quick outbound test
    try:
        urllib.request.urlopen("https://pypi.org/pypi/", timeout=3).close()
    except Exception as e:
        return CheckResult(
            passed=True,
            actual=f"network unavailable ({type(e).__name__})",
            expected="skipped",
            evidence=["  PyPI unreachable; skipping live check"],
        )

    missing: list[str] = []
    for f, ln, spec in deps[:30]:  # cap at 30 to keep audit fast
        name = (
            spec.replace(">=", " >=").replace("<", " <").replace("=", "").split()[0]
        )
        # Extras/PEP 508 markers
        name = name.split("[")[0]
        # normalize python module name -> distribution name (heuristic)
        url = f"https://pypi.org/pypi/{name}/json"
        try:
            with urllib.request.urlopen(url, timeout=5) as r:
                if r.status != 200:
                    missing.append(f"{f.relative_to(PROJECT_ROOT)}:{ln}: {spec} ({name} HTTP {r.status})")
        except urllib.error.HTTPError as e:
            if e.code == 404:
                missing.append(f"{f.relative_to(PROJECT_ROOT)}:{ln}: {spec} ({name} 404)")
        except Exception as e:
            missing.append(f"{f.relative_to(PROJECT_ROOT)}:{ln}: {spec} ({type(e).__name__})")

    if missing:
        return CheckResult(
            passed=False,
            actual=f"{len(missing)}/{len(deps)} deps missing on PyPI",
            expected="0 missing (sample of first 30 deps)",
            evidence=[f"  PROBLEM: {x}" for x in missing],
        )
    return CheckResult(
        passed=True,
        actual=f"{len(deps)}/{len(deps)} deps verified",
        expected="all deps exist on PyPI",
        evidence=[f"  sample size: {len(deps)}"],
    )


def check_10_llm_reviewer_stable_model() -> CheckResult:
    """Verify LLMReviewer doesn't default to a non-existent model name.

    gpt5 is NOT a real model. Default should be gpt-4o or similar.
    """
    reviewer = PROJECT_ROOT / "scripts" / "core" / "llm_reviewer.py"
    if not reviewer.exists():
        return CheckResult(
            passed=False,
            actual="llm_reviewer.py missing",
            expected="llm_reviewer.py exists",
            evidence=[],
        )
    text = reviewer.read_text()
    # Find the default value in __init__
    import re as _re
    defaults = _re.findall(r'judge_model:\s*str\s*=\s*"([^"]+)"', text)
    evidence = [f"  judge_model defaults found: {defaults}"]
    # Check if any default is gpt5
    bad_defaults = [d for d in defaults if d in ("gpt5", "gpt-5", "gpt5.4-mini")]
    if bad_defaults:
        return CheckResult(
            passed=False,
            actual=f"Non-existent model defaults: {bad_defaults}",
            expected='gpt-4o or similar stable model',
            evidence=evidence,
        )
    return CheckResult(
        passed=True,
        actual=f"All defaults stable: {defaults}",
        expected="No gpt5/gpt-5 defaults",
        evidence=evidence,
    )


# ────────────────────────────────────────────────────────────────────
# Registry
# ────────────────────────────────────────────────────────────────────


CHECKS: list[AuditCheck] = [
    AuditCheck(
        1,
        "PyPI package existence",
        "Verify whether finai-research-workflow is actually published",
        check_1_pypi_package_exists,
    ),
    AuditCheck(
        2,
        "Version string consistency",
        "Verify no stale v1.8.5 references exist",
        check_2_version_consistency,
    ),
    AuditCheck(
        3,
        "Numerical correctness tests exist",
        "Verify tests have assert_allclose calls (catches 'no tests' hallucinations)",
        check_3_numerical_tests_exist,
    ),
    AuditCheck(
        4,
        "Coverage threshold ≥ 10",
        "Verify CI coverage gate is reasonable (not 6%)",
        check_4_coverage_threshold,
    ),
    AuditCheck(
        5,
        "PyPI badges removed",
        "Verify README no longer links to fake PyPI badges",
        check_5_pypi_badges_redirected,
    ),
    AuditCheck(
        6,
        "Numerical tests pass",
        "Run tests/test_numerical_correctness.py and verify all pass",
        check_6_numerical_tests_pass,
    ),
    AuditCheck(
        7,
        "Demo outputs present (DISABLED — see check_7_demo_output_exists docstring)",
        "Disabled by user decision 2026-06-28 (audit_2026-06-28, Commit 0872901 删除了 demo_outputs/)",
        check_7_demo_output_exists,
    ),
    AuditCheck(
        8,
        "Cross-language validation present",
        "Verify R/Stata validation framework exists",
        check_8_validate_econometrics_exists,
    ),
    AuditCheck(
        9,
        "SSOT numbers match actual state",
        "Verify scripts/PROJECT_NUMBERS.json matches reality (root-cause fix for number hallucinations)",
        check_9_ssot_numbers_match_docs,
    ),
    AuditCheck(
        10,
        "LLMReviewer stable model",
        "Verify default judge_model is not gpt5 (non-existent)",
        check_10_llm_reviewer_stable_model,
    ),
    AuditCheck(
        11,
        "coverage omit size bounded",
        "Defense vs. audit-2026-07-04 P0-1 'omit to hide coverage' (cap=29)",
        check_11_omit_longtail_not_growing,
    ),
    AuditCheck(
        12,
        "CI fail-under floor",
        "Defense vs. audit-2026-07-04 P0-1 'lower threshold to pass' (floor=25 at PR-1; raise after PR-6)",
        check_12_fail_under_floor,
    ),
    AuditCheck(
        13,
        "Workflow YAML unquoted-colon check",
        "Defense: ci.yml YAML parse failures caused silent CI failures in PR-3 (a623563) and PR-4 (997abff). This check parses every .github/workflows/*.yml with PyYAML and flags any unquoted `name:` containing a colon.",
        check_13_workflow_yaml_unquoted_colons,
    ),
    AuditCheck(
        14,
        "diff-in-diff2 phantom dep",
        "Defense vs. phantom dep discovered by PR-4 test-full job: diff-in-diff2 does NOT exist on PyPI but was declared in requirements.txt and pyproject.toml. Code gracefully handles missing import via EstimatorUnavailableError.",
        check_14_diff_in_diff2_phantom_dep,
    ),
    AuditCheck(
        15,
        "PyPI deps existence (sample)",
        "Defense vs. typo'd / phantom deps: spot-checks first 30 deps from requirements.txt + pyproject.toml against PyPI. Skipped when network unavailable.",
        check_15_pypi_deps_exist,
    ),
]


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Defensive guard against audit hallucinations"
    )
    parser.add_argument("--check", help="comma-separated check IDs (default: all)")
    parser.add_argument("--json", action="store_true", help="JSON output")
    parser.add_argument(
        "--update-baseline",
        action="store_true",
        help="Update expected state file (for legitimate baseline changes)",
    )
    args = parser.parse_args()

    if args.check:
        ids = {int(x) for x in args.check.split(",")}
        selected = [c for c in CHECKS if c.id in ids]
    else:
        selected = CHECKS

    results: list[tuple[AuditCheck, CheckResult]] = []
    for check in selected:
        print(f"\n[Check {check.id}] {check.title}")
        print(f"  {check.description}")
        try:
            result = check.run()
        except Exception as e:
            result = CheckResult(
                passed=False, actual=f"error: {e}", expected="verifiable", evidence=[str(e)]
            )
        status = "✓ PASS" if result.passed else "✗ FAIL"
        print(f"  {status}")
        print(f"  actual:   {result.actual}")
        print(f"  expected: {result.expected}")
        for ev in result.evidence:
            print(ev)
        results.append((check, result))

    # Summary
    passed = sum(1 for _, r in results if r.passed)
    total = len(results)

    if args.json:
        out = {
            "passed": passed,
            "total": total,
            "results": [
                {
                    "id": c.id,
                    "title": c.title,
                    "passed": r.passed,
                    "actual": r.actual,
                    "expected": r.expected,
                    "evidence": r.evidence,
                }
                for c, r in results
            ],
        }
        print("\n" + json.dumps(out, indent=2, ensure_ascii=False))
    else:
        print("\n" + "=" * 60)
        print(f"AUDIT GUARD: {passed}/{total} checks passed")
        print("=" * 60)

    return 0 if passed == total else 1


if __name__ == "__main__":
    sys.exit(main())
