"""audit_guard.py — Defensive guard against LLM-generated audit hallucinations.

This script verifies audit claims BEFORE any human acts on them. It
runs cheap, deterministic checks (grep, file existence, test runs) that
catch the most common LLM-hallucination patterns:

  - Claiming a file exists that doesn't (e.g., "v1.8.5" in pyproject)
  - Claiming code is missing when it exists (e.g., "0 assert_allclose")
  - Claiming tests fail when they pass
  - Reporting stale numbers (e.g., coverage %)
  - Misreading API signatures

Usage:
    python scripts/audit_guard.py                      # run all checks
    python scripts/audit_guard.py --check 1,3,5        # specific checks
    python scripts/audit_guard.py --update-baseline    # refresh expected state
    python scripts/audit_guard.py --json               # machine-readable output

Exit code: 0 = all claims hold; 1 = at least one claim failed verification.

Design principle
----------------
Audit reports generated by LLMs frequently contain confident-sounding
claims that turn out to be false on inspection ("hallucinated fixes").
We accept that LLMs are useful for *finding* potential issues, but
NEVER trust them to verify their own findings. This script enforces
"show me the evidence" before any change is committed.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable


PROJECT_ROOT = Path(__file__).resolve().parent.parent


@dataclass
class AuditCheck:
    """Single verifiable audit claim."""

    id: int
    title: str
    description: str
    run: Callable[[], "CheckResult"]


@dataclass
class CheckResult:
    """Outcome of verifying a single audit claim."""

    passed: bool
    actual: str
    expected: str
    evidence: list[str] = field(default_factory=list)


# ────────────────────────────────────────────────────────────────────
# Individual checks
# ────────────────────────────────────────────────────────────────────


def _grep_count(pattern: str, glob: str, root: Path = PROJECT_ROOT) -> tuple[int, list[str]]:
    """Count files matching pattern; return (count, list_of_paths)."""
    cmd = ["grep", "-rln", "--include", glob, "--exclude-dir=.git", pattern, str(root)]
    res = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    paths = [p for p in res.stdout.strip().split("\n") if p]
    # Exclude audit-workflow.md (documents the v1.8.5 hallucination example)
    paths = [p for p in paths if not p.endswith("audit-workflow.md")]
    return len(paths), paths


def check_1_pypi_package_exists() -> CheckResult:
    """Audit claim: 'PyPI package finai-research-workflow doesn't exist.'

    We verify by hitting PyPI's JSON API. After 2026-07-11 publication
    the package DOES exist; this check flips its semantics accordingly.
    """
    import urllib.request
    import urllib.error

    evidence = []
    try:
        for name in ["finai-research-workflow", "finai_research_workflow"]:
            try:
                with urllib.request.urlopen(
                    f"https://pypi.org/pypi/{name}/json", timeout=5
                ) as r:
                    data = json.loads(r.read())
                version = data.get("info", {}).get("version", "?")
                evidence.append(f"  PyPI {name} v{version}: EXISTS (published)")
                return CheckResult(
                    passed=True,
                    actual="exists (published)",
                    expected="exists (published)",
                    evidence=evidence,
                )
            except urllib.error.HTTPError:
                evidence.append(f"  PyPI {name}: 404 (not published)")
            except Exception as e:
                evidence.append(f"  PyPI {name}: error {e}")
        # Neither name is published
        return CheckResult(
            passed=False,
            actual="not published",
            expected="published",
            evidence=evidence,
        )
    except Exception as e:
        return CheckResult(
            passed=False,
            actual=f"error: {e}",
            expected="verifiable",
            evidence=[str(e)],
        )


def check_2_version_consistency() -> CheckResult:
    """Audit claim: 'README says v1.8.5 but pyproject is 0.1.0.'

    We grep user-facing docs (README*, pyproject, setup.cfg, __init__.py)
    for version references and report counts. Internal docs are excluded
    because they may legitimately discuss version history.
    """
    files_to_check = ["README.md", "README_EN.md", "pyproject.toml", "setup.cfg", "setup.py"]
    v185_count = 0
    v185_paths = []
    for f in files_to_check:
        p = PROJECT_ROOT / f
        if not p.exists():
            continue
        cmd = ["grep", "-n", "v1\\.8\\.5", str(p)]
        res = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        lines = [m for m in res.stdout.strip().split("\n") if m]
        v185_count += len(lines)
        v185_paths.extend(f"{f}:{m.split(':', 1)[1]}" for m in lines)

    pyproject_version = "?"
    pyproject_path = PROJECT_ROOT / "pyproject.toml"
    if pyproject_path.exists():
        text = pyproject_path.read_text()
        m = re.search(r'^version\s*=\s*"([^"]+)"', text, re.MULTILINE)
        if m:
            pyproject_version = m.group(1)

    evidence = [
        f"  pyproject.toml version: {pyproject_version}",
        f"  'v1.8.5' in user-facing files: {v185_count}",
    ]
    if v185_paths:
        evidence.extend(f"    → {p}" for p in v185_paths[:5])

    if v185_count == 0:
        return CheckResult(
            passed=True,
            actual=f"0 v1.8.5 references, pyproject={pyproject_version}",
            expected="consistent",
            evidence=evidence,
        )
    return CheckResult(
        passed=False,
        actual=f"{v185_count} v1.8.5 references in user-facing files",
        expected="0 references",
        evidence=evidence,
    )


def check_3_numerical_tests_exist() -> CheckResult:
    """Audit claim: 'Tests lack numerical correctness — 0 assert_allclose.'

    We grep tests/ for assert_allclose calls.
    """
    cmd = ["grep", "-rn", "assert_allclose\\|assert_almost_equal", "tests/"]
    res = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    matches = [m for m in res.stdout.strip().split("\n") if m and not m.endswith(".pyc")]
    count = len(matches)
    evidence = [f"  assert_allclose/assert_almost_equal calls: {count}"]
    if matches:
        evidence.extend(f"    → {m}" for m in matches[:5])

    if count > 0:
        return CheckResult(
            passed=True,
            actual=f"{count} calls found",
            expected=">0 calls",
            evidence=evidence,
        )
    return CheckResult(
        passed=False,
        actual="0 calls",
        expected=">0 calls",
        evidence=evidence,
    )


def check_4_coverage_threshold() -> CheckResult:
    """Audit claim: 'CI sets fail_under=6 (~6%).'

    We grep ci.yml for the actual value.
    """
    ci_path = PROJECT_ROOT / ".github" / "workflows" / "ci.yml"
    if not ci_path.exists():
        return CheckResult(
            passed=False,
            actual="ci.yml missing",
            expected="ci.yml present",
            evidence=[],
        )
    text = ci_path.read_text()
    m = re.search(r"fail[-_]under=(\d+)", text)
    if not m:
        return CheckResult(
            passed=False,
            actual="no fail-under directive",
            expected="fail-under=N",
            evidence=[],
        )
    val = int(m.group(1))
    evidence = [f"  fail-under={val}"]
    return CheckResult(
        passed=val >= 10,
        actual=f"fail-under={val}",
        expected="≥10 (after audit fix)",
        evidence=evidence,
    )


def check_5_pypi_badges_redirected() -> CheckResult:
    """Audit claim: 'README has fake PyPI badges.'

    After 2026-07-11 real PyPI publication, README legitimately links to
    https://pypi.org/project/finai-research-workflow/. The previous
    "fake-badge detector" hard-coded zero links; we now verify that any
    such link RESOLVES (200 from PyPI).
    """
    cmd = ["grep", "-n", "pypi.org/project/finai\\|pypi/v/finai\\|pypi/dm/finai", "README.md", "README_EN.md"]
    res = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    matches = [m for m in res.stdout.strip().split("\n") if m]
    evidence = [f"  README PyPI links found: {len(matches)}"]
    if matches:
        evidence.extend(f"    → {m}" for m in matches[:5])

    if len(matches) == 0:
        return CheckResult(
            passed=True,
            actual="no PyPI mention",
            expected="at least 0 working PyPI links",
            evidence=evidence,
        )

    # Verify each link actually resolves (200 from PyPI = real link)
    import urllib.request
    import urllib.error
    import re as _re
    bad = []
    for m in matches:
        url_m = _re.search(r"https?://[^\s)]+", m)
        if url_m:
            url = url_m.group(0).rstrip(")")
            try:
                with urllib.request.urlopen(url, timeout=5) as r:
                    if r.status != 200:
                        bad.append((url, r.status))
            except Exception as exc:
                bad.append((url, str(exc)[:50]))
    evidence.append(f"  broken PyPI links: {len(bad)}")
    for u, s in bad[:5]:
        evidence.append(f"    → HTTP {s}: {u}")

    if len(bad) == 0:
        return CheckResult(
            passed=True,
            actual=f"{len(matches)} working PyPI links",
            expected="all links resolve",
            evidence=evidence,
        )
    return CheckResult(
        passed=False,
        actual=f"{len(bad)} broken PyPI links",
        expected="all links resolve",
        evidence=evidence,
    )


def check_6_numerical_tests_pass() -> CheckResult:
    """Audit claim: 'Existing tests don't catch numerical regressions.'

    We run tests/test_numerical_correctness.py and verify all pass.
    """
    test_file = PROJECT_ROOT / "tests" / "test_numerical_correctness.py"
    if not test_file.exists():
        return CheckResult(
            passed=False,
            actual="test file missing",
            expected="test_numerical_correctness.py exists",
            evidence=[],
        )
    cmd = [sys.executable, "-m", "pytest", str(test_file), "-q", "--tb=no"]
    res = subprocess.run(cmd, capture_output=True, text=True, timeout=180, cwd=PROJECT_ROOT)
    # Parse last line for "N passed"
    summary = ""
    for line in res.stdout.splitlines() + res.stderr.splitlines():
        if "passed" in line and ("in " in line or "s)" in line):
            summary = line.strip()
    evidence = [f"  pytest exit: {res.returncode}", f"  summary: {summary}"]
    if res.returncode == 0:
        return CheckResult(
            passed=True,
            actual=f"all pass",
            expected="all pass",
            evidence=evidence,
        )
    return CheckResult(
        passed=False,
        actual=f"exit={res.returncode}",
        expected="exit=0",
        evidence=evidence,
    )


def check_7_demo_output_exists() -> CheckResult:  # pragma: no cover
    """Audit claim: 'No demo PDFs in papers/'.

    Disabled 2026-06-28 by user decision:
    - User removed papers/demo_outputs/ in commit 0872901
      (用户观点："当前留存只有负面影响")
    - Check 7 conflicted with that decision
    - Kept function as no-op stub so other code that imports it doesn't break
    """
    return CheckResult(
        passed=True,
        actual="disabled (user decision 2026-06-28)",
        expected="N/A",
        evidence=[],
    )
    tex_files = list(demo_dir.glob("*.tex"))
    pdf_files = list(demo_dir.glob("*.pdf"))
    evidence = [f"  .tex files: {len(tex_files)}", f"  .pdf files: {len(pdf_files)}"]
    if tex_files or pdf_files:
        return CheckResult(
            passed=True,
            actual=f"{len(tex_files)} tex, {len(pdf_files)} pdf",
            expected="≥1 demo output",
            evidence=evidence,
        )
    return CheckResult(
        passed=False,
        actual="empty",
        expected="≥1 demo output",
        evidence=evidence,
    )


def check_8_validate_econometrics_exists() -> CheckResult:
    """Audit claim: 'No R/Stata cross-validation.'

    Verify scripts/validate_econometrics.py exists and supports Stata.
    """
    target = PROJECT_ROOT / "scripts" / "validate_econometrics.py"
    if not target.exists():
        return CheckResult(
            passed=False,
            actual="missing",
            expected="validate_econometrics.py exists",
            evidence=[],
        )
    text = target.read_text()
    text_lower = text.lower()
    has_stata = "stata" in text_lower and ("reghdfe" in text_lower or "validate_against_stata" in text_lower)
    has_r = "fixest" in text_lower or "rscript" in text_lower or "validate_against_r" in text_lower
    evidence = [
        f"  Stata validation: {'yes' if has_stata else 'no'}",
        f"  R validation: {'yes' if has_r else 'no'}",
    ]
    if has_stata or has_r:
        return CheckResult(
            passed=True,
            actual=f"Stata={has_stata}, R={has_r}",
            expected="≥1 cross-validation",
            evidence=evidence,
        )
    return CheckResult(
        passed=False,
        actual="neither",
        expected="≥1 cross-validation",
            evidence=evidence,
        )


def check_9_ssot_numbers_match_docs() -> CheckResult:
    """Verify that PROJECT_NUMBERS.json (SSOT) matches the actual state.

    This is the root-cause fix for repeated number-hallucination audits:
    numbers drift when maintained in 5+ docs independently. The SSOT
    (scripts/PROJECT_NUMBERS.json) is the single source of truth; docs must
    be updated from it via sync_numbers.py --apply, not manually.
    """
    ssot_path = PROJECT_ROOT / "scripts" / "PROJECT_NUMBERS.json"
    if not ssot_path.exists():
        return CheckResult(
            passed=False,
            actual="SSOT file missing",
            expected="scripts/PROJECT_NUMBERS.json exists",
            evidence=[],
        )
    import json as _json
    ssot = _json.loads(ssot_path.read_text())

    # Verify MCP directory count
    import subprocess as _sub
    res = _sub.run(
        ["sh", "-c", f"ls {PROJECT_ROOT}/mcp_servers/ | grep '^user_' | wc -l"],
        capture_output=True, text=True,
    )
    actual_mcp = int(res.stdout.strip())
    ssot_mcp = ssot["mcp"]["total_directories"]
    mcp_ok = actual_mcp == ssot_mcp

    # Verify stub servers have tools/
    stub_issues = []
    for stub_name in ssot["mcp"].get("stub_servers", []):
        tools_dir = PROJECT_ROOT / "mcp_servers" / stub_name / "tools"
        if not tools_dir.exists():
            stub_issues.append(f"  {stub_name}: no tools/ directory")
        elif not list(tools_dir.glob("*.json")):
            stub_issues.append(f"  {stub_name}: tools/ is empty")
    stub_ok = len(stub_issues) == 0

    evidence = [
        f"  SSOT MCP directories: {ssot_mcp}, actual: {actual_mcp} → {'OK' if mcp_ok else 'MISMATCH'}",
        f"  SSOT stubs: {len(ssot['mcp'].get('stub_servers', []))}, actual stub issues: {len(stub_issues)}",
    ]
    if stub_issues:
        evidence.extend(stub_issues[:5])

    all_ok = mcp_ok and stub_ok
    return CheckResult(
        passed=all_ok,
        actual=f"MCP match={mcp_ok}, stubs={len(stub_issues)} issues",
        expected="SSOT matches actual state",
        evidence=evidence,
    )


def check_11_omit_longtail_not_growing() -> CheckResult:
    """Audit claim (audit-2026-07-04 P0-1): 'CI 覆盖率凑数通过新增 omit 藏分母'.

    Defense: bound the size of [tool.coverage.run] omit list. If it
    grows beyond a known set of legitimate CLI / DEPRECATED modules,
    this is a hallucinated-fix attempt and must be rejected.
    """
    p = PROJECT_ROOT / "pyproject.toml"
    if not p.exists():
        return CheckResult(False, "pyproject.toml missing", "exists", [])
    text = p.read_text()
    block_start = text.find("[tool.coverage.run]")
    if block_start < 0:
        return CheckResult(False, "no [tool.coverage.run] block", "present", [])
    rest = text[block_start:]
    # Stop at next TOML section header (line starting with `[name]`).
    block_lines = []
    lines = rest.splitlines(keepends=True)
    for idx, ln in enumerate(lines):
        if idx == 0:
            block_lines.append(ln)
            continue
        s = ln.strip()
        if s.startswith("[") and s.endswith("]") and not s.startswith("#"):
            break
        block_lines.append(ln)
    block = "".join(block_lines)
    in_omit = False
    omit_lines = []
    for ln in block.splitlines():
        s = ln.strip()
        if s.startswith("omit"):
            in_omit = True
            continue
        if in_omit:
            if s.startswith("]"):
                in_omit = False
                continue
            if s.startswith('"') and ".py" in s:
                omit_lines.append(s)
    count = len(omit_lines)
    # 2026-07-04 baseline (post PR-1): ~24 CLI/DEPRECATED entries.
    # Cap at 29 to allow legitimate additions; bigger is suspicious.
    cap = 29
    evidence = [f"  omit entries: {count}", f"  cap: {cap}"]
    if omit_lines:
        evidence.extend(f"    -> {x[:60]}" for x in omit_lines[:3])
    return CheckResult(
        passed=count <= cap,
        actual=f"{count} entries",
        expected=f"<= {cap}",
        evidence=evidence,
    )


def check_12_fail_under_floor() -> CheckResult:
    """Audit claim (audit-2026-07-04 P0-1): 'fail-under is repeatedly lowered
    (6 -> 3 -> 15 -> 25)'.

    Defense: enforce a minimum floor on fail-under. The floor is
    intentionally conservative (=25) at PR-1 time because removing the
    9 "CI not-imported" omit entries drops the apparent coverage from
    a padded 25-30% to a real 26-27%. PR-6 will add ~425 real tests to
    push coverage naturally above 30%, at which point this check's
    floor should be raised in lockstep.

    Audit guard against silent threshold drift downward.
    """
    ci = PROJECT_ROOT / ".github" / "workflows" / "ci.yml"
    if not ci.exists():
        return CheckResult(False, "ci.yml missing", "present", [])
    text = ci.read_text()
    import re
    matches = re.findall(r"fail[-_]under=(\d+)", text)
    if not matches:
        return CheckResult(False, "no fail-under directive", ">=25", [])
    vals = [int(x) for x in matches]
    min_v = min(vals)
    evidence = [
        f"  fail-under values found: {vals}",
        f"  minimum: {min_v}",
        f"  audit-2026-07-04 floor: 25 (PR-1) -> 28 (PR-6 import smoke); 60% deferred to PR-8",
    ]
    if min_v >= 28:
        return CheckResult(
            passed=True,
            actual=f"min={min_v}",
            expected=">=28 (audit-2026-07-04 floor at PR-6)",
            evidence=evidence,
        )
    return CheckResult(
        passed=False,
        actual=f"min={min_v}",
        expected=">=28",
        evidence=evidence,
    )


def check_13_workflow_yaml_unquoted_colons() -> CheckResult:
    """Verify all GitHub workflow YAML files parse, and warns on quoted-on-need
    patterns.

    Defense: dynamically parse every .yml/.yaml under .github/workflows/ with
    PyYAML, and additionally scan for the pattern 'name: <unquoted text with
    colon>' as a heuristic to catch the bug class even when other YAML in the
    file happens to parse (e.g. unquoted colons inside a `run:` block).
    """
    evidence: list[str] = []
    bad_files: list[str] = []

    for p in sorted((PROJECT_ROOT / ".github").rglob("*.y*ml")):
        rel = p.relative_to(PROJECT_ROOT)
        evidence.append(f"  parsing: {rel}")
        try:
            import yaml  # type: ignore[import-untyped]

            yaml.safe_load(p.read_text(encoding="utf-8"))
        except Exception as e:
            bad_files.append(f"{rel}: {type(e).__name__}: {e}")
        # Heuristic: scan for unquoted `name:` containing a colon.
        for i, line in enumerate(p.read_text(encoding="utf-8").splitlines(), 1):
            stripped = line.lstrip()
            if not stripped.startswith("- name:") and not stripped.startswith("name:"):
                continue
            # Extract value after `name:`.
            val = stripped.split("name:", 1)[1].lstrip()
            # If the value is unquoted and contains a colon, that's the bug.
            if val and not val.startswith('"') and not val.startswith("'"):
                if ":" in val:
                    bad_files.append(
                        f"{rel}:{i}: name field contains unquoted colon: {line.strip()!r}"
                    )

    if bad_files:
        return CheckResult(
            passed=False,
            actual=f"{len(bad_files)} issue(s)",
            expected="0 (every workflow YAML must parse; no unquoted `name:` colons)",
            evidence=evidence + [f"  PROBLEM: {x}" for x in bad_files],
        )
    return CheckResult(
        passed=True,
        actual="0 issues",
        expected="0",
        evidence=evidence,
    )


def check_14_diff_in_diff2_phantom_dep() -> CheckResult:
    """`diff-in-diff2` does not exist on PyPI as of 2026-07-04.

    PR-4's test-full job discovered this when `pip install -r requirements.txt`
    failed with `ERROR: Could not find a version that satisfies the requirement
    diff-in-diff2>=1.0.0`. The package was referenced in:
      * requirements.txt line 91
      * pyproject.toml [project.optional-dependencies.econometrics]
      * multiple docs (CLAUDE.md, README*.md)
      * scripts/research_framework/modern_did.py via `import diff_in_diff2`

    Defense: verify no active (uncommented) reference to `diff-in-diff2` or
    `diff_in_diff2` exists in requirements.txt, pyproject.toml, or any
    tracked source file. Commented-out lines are allowed (they document the
    historic decision).

    If anyone re-adds this dep without verifying PyPI existence, this check
    will fail and the related PR will not pass CI.
    """
    refs: list[str] = []
    pyproject = PROJECT_ROOT / "pyproject.toml"
    req = PROJECT_ROOT / "requirements.txt"

    for f in [pyproject, req]:
        if not f.exists():
            continue
        for i, line in enumerate(f.read_text(encoding="utf-8").splitlines(), 1):
            stripped = line.strip()
            if stripped.startswith("#"):
                continue
            if "diff-in-diff2" in line or "diff_in_diff2" in line:
                refs.append(f"active install: {f.relative_to(PROJECT_ROOT)}:{i}: {stripped}")

    # In source code, `import diff_in_diff2` is ALLOWED (graceful fallback
    # via EstimatorUnavailableError in scripts/research_framework/modern_did.py).
    # We only flag install directives in requirements files here.

    if refs:
        return CheckResult(
            passed=False,
            actual=f"{len(refs)} active install reference(s)",
            expected="0 (phantom dep — commented references or error-message strings only)",
            evidence=[f"  PROBLEM: {x}" for x in refs],
        )
    return CheckResult(
        passed=True,
        actual="0 active install references",
        expected="0",
        evidence=[
            "  verified: requirements.txt comment only",
            "  pyproject.toml comment only",
            "  runtime imports allowed (graceful EstimatorUnavailableError)",
        ],
    )


def check_15_pypi_deps_exist() -> CheckResult:
    """Spot-check every pip-installable dep declared in requirements.txt and
    pyproject.toml actually exists on PyPI.

    audit-2026-07-04 PR-4 caught `diff-in-diff2` (which doesn't exist) this
    way. Generalizing: for each non-comment line containing a `>=` or `==`
    pin, verify PyPI has at least one matching version. This is run on demand
    (not in CI by default) because PyPI is rate-limited, but it's a powerful
    audit signal.

    Skipped when network is unavailable.
    """
    import urllib.error
    import urllib.request

    deps: list[tuple[Path, int, str]] = []  # (file, line, dep_spec)
    # PEP 621 metadata keys that contain ">=" but are NOT PyPI deps
    _NON_DEP_KEYS = (
        "requires-python",
        "requires",
        "build-requires",
    )
    for f in [PROJECT_ROOT / "pyproject.toml", PROJECT_ROOT / "requirements.txt"]:
        if not f.exists():
            continue
        for i, line in enumerate(f.read_text(encoding="utf-8").splitlines(), 1):
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            # Skip PEP 621 metadata fields that look like deps but aren't
            if any(stripped.startswith(f"{k} ") or stripped.startswith(f"{k}=")
                   for k in _NON_DEP_KEYS):
                continue
            for tok in stripped.replace(" ", ",").split(","):
                tok = tok.strip().strip('"').strip("'")
                if ">=" in tok and not tok.startswith("-"):
                    deps.append((f, i, tok))
                    break
            else:
                continue

    # Quick outbound test
    try:
        urllib.request.urlopen("https://pypi.org/pypi/", timeout=3).close()
    except Exception as e:
        return CheckResult(
            passed=True,
            actual=f"network unavailable ({type(e).__name__})",
            expected="skipped",
            evidence=["  PyPI unreachable; skipping live check"],
        )

    missing: list[str] = []
    skipped: list[str] = []
    for f, ln, spec in deps[:30]:  # cap at 30 to keep audit fast
        name = (
            spec.replace(">=", " >=").replace("<", " <").replace("=", "").split()[0]
        )
        # Extras/PEP 508 markers
        name = name.split("[")[0]
        # normalize python module name -> distribution name (heuristic)
        url = f"https://pypi.org/pypi/{name}/json"
        try:
            with urllib.request.urlopen(url, timeout=5) as r:
                if r.status != 200:
                    missing.append(f"{f.relative_to(PROJECT_ROOT)}:{ln}: {spec} ({name} HTTP {r.status})")
        except urllib.error.HTTPError as e:
            if e.code == 404:
                missing.append(f"{f.relative_to(PROJECT_ROOT)}:{ln}: {spec} ({name} 404)")
            else:
                skipped.append(f"{f.relative_to(PROJECT_ROOT)}:{ln}: {spec} (HTTP {e.code})")
        except Exception as e:
            skipped.append(f"{f.relative_to(PROJECT_ROOT)}:{ln}: {spec} ({type(e).__name__})")

    # If any dep check was skipped (network error), treat as informational pass
    if skipped and not missing:
        return CheckResult(
            passed=True,
            actual=f"0 missing, {len(skipped)} skipped (network issue)",
            expected="0 missing or skipped",
            evidence=[f"  SKIPPED (network error): {x}" for x in skipped],
        )

    if missing:
        return CheckResult(
            passed=False,
            actual=f"{len(missing)}/{len(deps)} deps missing on PyPI",
            expected="0 missing (sample of first 30 deps)",
            evidence=[f"  PROBLEM: {x}" for x in missing],
        )
    return CheckResult(
        passed=True,
        actual=f"{len(deps)}/{len(deps)} deps verified",
        expected="all deps exist on PyPI",
        evidence=[f"  sample size: {len(deps)}"],
    )


def check_10_llm_reviewer_stable_model() -> CheckResult:
    """Verify LLMReviewer doesn't default to a non-existent model name.

    gpt5 is NOT a real model. Default should be gpt-4o or similar.
    """
    reviewer = PROJECT_ROOT / "scripts" / "core" / "llm_reviewer.py"
    if not reviewer.exists():
        return CheckResult(
            passed=False,
            actual="llm_reviewer.py missing",
            expected="llm_reviewer.py exists",
            evidence=[],
        )
    text = reviewer.read_text()
    # Find the default value in __init__
    import re as _re
    defaults = _re.findall(r'judge_model:\s*str\s*=\s*"([^"]+)"', text)
    evidence = [f"  judge_model defaults found: {defaults}"]
    # Check if any default is gpt5
    bad_defaults = [d for d in defaults if d in ("gpt5", "gpt-5", "gpt5.4-mini")]
    if bad_defaults:
        return CheckResult(
            passed=False,
            actual=f"Non-existent model defaults: {bad_defaults}",
            expected='gpt-4o or similar stable model',
            evidence=evidence,
        )
    return CheckResult(
        passed=True,
        actual=f"All defaults stable: {defaults}",
        expected="No gpt5/gpt-5 defaults",
        evidence=evidence,
    )


# ────────────────────────────────────────────────────────────────────
# Check 16: version drift (defense for 2026-07-11 audit findings)
# ────────────────────────────────────────────────────────────────────


def _check_reproducibility_layer() -> CheckResult:
    """T3 audit 2026-07-12: verify normalize.py exists with required exports."""
    import ast, sys
    root = Path(__file__).parent.parent
    norm_path = root / "scripts" / "core" / "normalize.py"
    if not norm_path.exists():
        return CheckResult(
            passed=False,
            expected="normalize.py exists",
            actual=f"NOT FOUND at {norm_path}",
        )
    # Verify key exports
    src = norm_path.read_text(encoding="utf-8")
    exports = [
        "setup_reproducible_env",
        "normalize_json_dumps",
        "normalize_path",
        "normalize_datetime",
        "normalize_line_endings",
        "normalize_random_seed",
        "LIMITATIONS",
    ]
    missing = [e for e in exports if f"def {e}" not in src and e not in src]
    if missing:
        return CheckResult(
            passed=False,
            expected="all required functions exported",
            actual=f"missing: {missing}",
        )
    return CheckResult(
        passed=True,
        expected="all required functions exported",
        actual=f"normalize.py OK ({len(src)} bytes)",
    )


def _check_mcp_registration_health() -> CheckResult:
    """T4 audit 2026-07-12: verify all mcp.json registered servers have
    valid command + module path. External whitelist (e.g. user_pdf_excel
    pointing outside this repo) is allowed but flagged."""
    import json, re
    from pathlib import Path
    try:
        from scripts.core.platform import get_mcp_config
    except ImportError:
        return CheckResult(
            passed=False,
            expected="scripts.core.platform importable",
            actual="import failed",
        )
    try:
        cfg = get_mcp_config()
    except Exception as e:
        return CheckResult(
            passed=False,
            expected="mcp.json loadable",
            actual=f"load failed: {e}",
        )
    servers = cfg.get("mcpServers", {})
    if not servers:
        return CheckResult(
            passed=False,
            expected="at least 1 MCP server registered",
            actual="0 servers found",
        )

    EXTERNAL_WHITELIST_PATHS = (
        "/Users/xuzheyi/Desktop/pdf-to-excel",  # external pdf-to-excel tool
    )

    broken: list[str] = []
    for name, entry in servers.items():
        cmd = entry.get("command", "")
        # Skip external-whitelisted entries (operator-managed, may not exist locally)
        if any(wh in cmd for wh in EXTERNAL_WHITELIST_PATHS):
            continue
        if cmd and not Path(cmd).exists():
            broken.append(f"{name}: cmd missing ({cmd})")
            continue
        # find sys.path.insert target + from user_xxx.server import
        path_str = None
        mod_name = None
        for a in entry.get("args", []):
            if isinstance(a, str) and "sys.path.insert" in a:
                m = re.search(r"insert\(0, ['\"]([^'\"]+)", a)
                if m:
                    path_str = m.group(1)
            if isinstance(a, str) and "from user_" in a:
                m2 = re.findall(r"from (user_\w+)", a)
                if m2:
                    mod_name = m2[0]
        if path_str:
            # Skip external-whitelisted paths
            if any(wh in path_str for wh in EXTERNAL_WHITELIST_PATHS):
                continue
            if not Path(path_str).exists():
                broken.append(f"{name}: path missing ({path_str})")
                continue
            if mod_name:
                server_py = Path(path_str) / mod_name / "server.py"
                if not server_py.exists():
                    broken.append(f"{name}: module {mod_name} not at {server_py}")

    if broken:
        return CheckResult(
            passed=False,
            expected="all registered servers have valid command+path+module",
            actual=f"broken: {broken[:5]}",
        )
    return CheckResult(
        passed=True,
        expected="all registered servers have valid command+path+module",
        actual=f"{len(servers)} servers OK (incl. external whitelist)",
    )


def _check_hitl_coverage() -> CheckResult:
    """T6 audit 2026-07-12: verify research_framework pipeline.py calls
    _hitl_pause() at the data-loaded and regression-run stages, AND that
    the --no-hitl flag exists for batch runs.

    Bug fix context: prior to 2026-07-12 the pipeline ran fully autonomously
    from topic → regression → Word doc, only pausing on topic change. Users
    had no chance to inspect the panel, the data-source plan, or the
    coefficient signs/magnitudes before they were written to disk.
    """
    root = Path(__file__).parent.parent
    p = root / "scripts" / "research_framework" / "pipeline.py"
    if not p.exists():
        return CheckResult(
            passed=False,
            expected="research_framework/pipeline.py exists",
            actual="NOT FOUND",
        )
    src = p.read_text(encoding="utf-8")

    # Required gate calls (>= 2 stages)
    required_calls = [
        "_hitl_pause(\n        stage_id=\"data_loaded\"",
        "_hitl_pause(\n        stage_id=\"regression_run\"",
    ]
    missing_calls = [c for c in required_calls if c not in src]

    # Required CLI flag
    has_no_hitl = '"--no-hitl"' in src or "'--no-hitl'" in src

    # Verify the function is actually defined
    has_func_def = "def _hitl_pause(" in src

    if missing_calls:
        return CheckResult(
            passed=False,
            expected="_hitl_pause called at data_loaded + regression_run",
            actual=f"missing: {len(missing_calls)} call(s)",
        )
    if not has_no_hitl:
        return CheckResult(
            passed=False,
            expected="--no-hitl CLI flag exists for batch runs",
            actual="not found in argparse",
        )
    if not has_func_def:
        return CheckResult(
            passed=False,
            expected="_hitl_pause() function defined",
            actual="not found",
        )
    return CheckResult(
        passed=True,
        expected="_hitl_pause called at data_loaded + regression_run",
        actual=f"{len(required_calls)} gates wired + --no-hitl flag present",
    )


def _check_health_check_skip_flags() -> CheckResult:
    """T7 audit 2026-07-12: verify scripts/health_check.py exposes
    --ignore-data-source and --ignore-api-key CLI flags.

    Bug fix context: prior version reported "missing API key" / "data source
    not configured" as hard failures with no escape hatch. Operators had no
    documented way to suppress paid-MCP warnings when intentionally absent.
    """
    root = Path(__file__).parent.parent
    p = root / "scripts" / "health_check.py"
    if not p.exists():
        return CheckResult(
            passed=False,
            expected="health_check.py exists",
            actual="NOT FOUND",
        )
    src = p.read_text(encoding="utf-8")
    required = [
        "\"--ignore-data-source\"",
        "\"--ignore-api-key\"",
        "ignore_data_source: bool = False",
        "ignore_api_key: bool = False",
    ]
    missing = [r for r in required if r not in src]
    if missing:
        return CheckResult(
            passed=False,
            expected="all 4 skip-flag tokens present in health_check.py",
            actual=f"missing: {missing}",
        )
    return CheckResult(
        passed=True,
        expected="all 4 skip-flag tokens present in health_check.py",
        actual="--ignore-data-source + --ignore-api-key wired + threaded to run_diagnostic()",
    )


def check_16_version_drift() -> CheckResult:
    """Audit claim: 'Multiple files hardcode APP_VERSION = "1.0.0" or banner v1.0.0'.

    Defense: scan scripts/**/*.py for literal version strings that don't
    match pyproject.toml. Triggered by the 2026-07-11 audit finding that
    scripts/cli.py, 3 MCP servers, and scripts/gen_architecture_diagrams.py
    all had hardcoded '1.0.0'.
    """
    import re as _re

    # Get canonical version
    pyproject = PROJECT_ROOT / "pyproject.toml"
    if not pyproject.exists():
        return CheckResult(
            passed=True,
            actual="no pyproject.toml",
            expected="consistent",
            evidence=[],
        )
    text = pyproject.read_text()
    m = _re.search(r'^version\s*=\s*"([^"]+)"', text, re.MULTILINE)
    if not m:
        return CheckResult(
            passed=False,
            actual="pyproject.toml has no version",
            expected="version line present",
            evidence=[],
        )
    canonical = m.group(1)  # e.g. "0.2.0-alpha"

    # Files to scan for hardcoded version drift
    scan_patterns = [
        r'APP_VERSION\s*=\s*"(?P<v1>[0-9]+\.[0-9]+\.[0-9]+)"',
        r"v(?P<v2>[0-9]+\.[0-9]+\.[0-9]+)\s*·",
        r'= "v(?P<v3>[0-9]+\.[0-9]+\.[0-9]+)"',
    ]
    import re as _re

    # Get canonical version
    pyproject = PROJECT_ROOT / "pyproject.toml"
    if not pyproject.exists():
        return CheckResult(
            passed=True,
            actual="no pyproject.toml",
            expected="consistent",
            evidence=[],
        )
    text = pyproject.read_text()
    m = _re.search(r'^version\s*=\s*"([^"]+)"', text, re.MULTILINE)
    if not m:
        return CheckResult(
            passed=False,
            actual="pyproject.toml has no version",
            expected="version line present",
            evidence=[],
        )
    canonical = m.group(1)  # e.g. "0.2.0-alpha"

    # Files to scan for hardcoded version drift
    scan_patterns = [
        r'APP_VERSION\s*=\s*"(?P<v1>[0-9]+\.[0-9]+\.[0-9]+)"',
        r"v(?P<v2>[0-9]+\.[0-9]+\.[0-9]+)\s*·",
        r'= "v(?P<v3>[0-9]+\.[0-9]+\.[0-9]+)"',
    ]
    combined_re = _re.compile("|".join(scan_patterns))

    drift_files: list[tuple[str, str, int]] = []
    scanned = 0
    try:
        from glob import glob as _glob

        for fpath in _glob(
            str(PROJECT_ROOT / "scripts" / "**" / "*.py"), recursive=True
        ):
            scanned += 1
            if "__pycache__" in fpath or "/legacy/" in fpath:
                continue
            # Skip the legitimate sub-pyproject reference files
            if fpath.endswith("/mcp_servers/_shared/_version.py"):
                continue
            # Skip audit guard docstring (it cites v1.8.5 as known hallucination)
            if fpath.endswith("audit_guard.py"):
                continue
            # Skip files documenting the v1.0.0 fix history (e.g. CHANGELOG mentions)
            with open(fpath) as fp:
                for lineno, line in enumerate(fp, start=1):
                    for match in combined_re.finditer(line):
                        # extract version from whichever named group matched
                        v_group = (
                            match.group("v1")
                            or match.group("v2")
                            or match.group("v3")
                        )
                        if v_group and v_group != canonical:
                            try:
                                rel = str(Path(fpath).relative_to(PROJECT_ROOT))
                            except ValueError:
                                rel = fpath
                            drift_files.append((rel, v_group, lineno))
    except Exception as e:
        return CheckResult(
            passed=False,
            actual=f"scan error: {e}",
            expected="scannable",
            evidence=[str(e)],
        )

    evidence = [
        f"  canonical version: {canonical}",
        f"  files scanned:    {scanned}",
    ]
    if drift_files:
        evidence.append(
            f"  DRIFT FOUND ({len(drift_files)} occurrence(s)):"
        )
        for rel, found, lineno in drift_files[:10]:
            evidence.append(
                f"    → {rel}:{lineno}  '{found}' (expected '{canonical}')"
            )

    if drift_files:
        return CheckResult(
            passed=False,
            actual=f"{len(drift_files)} hardcoded version drift occurrences",
            expected="0 (all must match pyproject.toml)",
            evidence=evidence,
        )
    return CheckResult(
        passed=True,
        actual="0 drift (all hardcoded versions match pyproject)",
        expected="0 drift",
        evidence=evidence,
    )


# ────────────────────────────────────────────────────────────────────
# Check 17: Anti-pattern detection (T001 / T002 / T003 audit_fix_2026_07_12)
# ────────────────────────────────────────────────────────────────────


def check_17_no_research_integrity_anti_patterns() -> CheckResult:
    """Audit claim: 'No mechanism-tautology, no heuristic-sig, no short-panel DID silence.'

    Defense: scan key research modules for known anti-patterns that would
    constitute academic integrity issues (or statistical misleading):

    T001 (mechanism tautology): us_esg_regression.py must NOT construct
        proxy variables as linear functions of treatment variables.
    T002 (heuristic significance): synthetic_control.py .sig property must
        NOT use raw RMSPE ratio heuristic (must use permutation p-value).
    T003 (short-panel silence): us_esg_regression.py must emit warning when
        T_post < 5 (Roth & Sant'Anna 2023).

    Triggers PASS if NONE of the anti-patterns are detected, FAIL otherwise.
    """
    import re as _re
    findings: list[str] = []

    # ── T001 check ─────────────────────────────────────────────────
    t001_path = PROJECT_ROOT / "scripts" / "us_esg_regression.py"
    if t001_path.exists():
        text = t001_path.read_text(encoding="utf-8")
        # The 3 tautological constructions:
        tautology_patterns = [
            (r'df_mech\["analyst_cov_proxy"\]\s*=\s*df_mech\["ln_assets"\]\s*\*\s*2\.8',
             "T001: analyst_cov_proxy = ln_assets * 2.8 tautology"),
            (r'df_mech\["cds_proxy"\]\s*=\s*120\s*-\s*42',
             "T001: cds_proxy = 120 - 42 * esg_high tautology"),
            (r'df_mech\["rating_proxy"\]\s*=\s*4\s*\+\s*1\.5',
             "T001: rating_proxy = 4 + 1.5 * esg_high tautology"),
        ]
        for pattern, desc in tautology_patterns:
            if _re.search(pattern, text):
                findings.append(f"us_esg_regression.py: {desc}")
        # Positive: audit_fix marker must be present
        if "audit_fix_2026_07_12" not in text:
            findings.append("us_esg_regression.py: missing audit_fix_2026_07_12 marker")

    # ── T002 check ─────────────────────────────────────────────────
    t002_path = PROJECT_ROOT / "scripts" / "research_framework" / "synthetic_control.py"
    if t002_path.exists():
        text = t002_path.read_text(encoding="utf-8")
        # Find .sig property block
        sig_match = _re.search(
            r"    @property\n    def sig\(self\) -> str:\n(.*?)(?=\n    @property|\n    def \w)",
            text, _re.DOTALL,
        )
        if sig_match:
            sig_body = sig_match.group(1)
            # If sig body references "rmspe_ratio" without "_sig" suffix → heuristic
            cleaned = sig_body.lower().replace("rmspe_ratio_sig", "")
            if "rmspe_ratio" in cleaned:
                findings.append(
                    "synthetic_control.py: .sig property still uses RMSPE ratio heuristic (T002 not fixed)"
                )
            # .sig must reference permutation
            if "permutation" not in sig_body.lower():
                findings.append(
                    "synthetic_control.py: .sig property does not reference permutation p-value (T002 not fixed)"
                )
        else:
            findings.append("synthetic_control.py: cannot locate .sig property")
        # Must have rmspe_ratio_sig (legacy) accessor
        if "def rmspe_ratio_sig" not in text:
            findings.append("synthetic_control.py: missing legacy rmspe_ratio_sig accessor")
        # Must have audit_fix marker
        if "audit_fix_2026_07_12" not in text:
            findings.append("synthetic_control.py: missing audit_fix_2026_07_12 marker")

    # ── T003 check ─────────────────────────────────────────────────
    if t001_path.exists():
        text = t001_path.read_text(encoding="utf-8")
        if "n_post < 5" not in text and "n_post &lt; 5" not in text:
            findings.append(
                "us_esg_regression.py: missing short-panel DID warning (T003 not fixed)"
            )
        # Must cite Roth & Sant'Anna
        if "Roth" not in text or "Sant'Anna" not in text and "Sant" not in text:
            findings.append(
                "us_esg_regression.py: missing Roth & Sant'Anna (2023) citation (T003 not fixed)"
            )

    if findings:
        return CheckResult(
            passed=False,
            actual=f"{len(findings)} anti-pattern finding(s)",
            expected="0 anti-patterns",
            evidence=findings[:10],
        )

    return CheckResult(
        passed=True,
        actual="0 anti-patterns (T001/T002/T003 audit fixes intact)",
        expected="0 anti-patterns",
        evidence=["T001: mechanism tautology removed",
                  "T002: .sig uses permutation p-value",
                  "T003: short-panel DID warning present"],
    )


# ────────────────────────────────────────────────────────────────────
# Registry
# ────────────────────────────────────────────────────────────────────


CHECKS: list[AuditCheck] = [
    AuditCheck(
        1,
        "PyPI package existence",
        "Verify whether finai-research-workflow is actually published",
        check_1_pypi_package_exists,
    ),
    AuditCheck(
        2,
        "Version string consistency",
        "Verify no stale v1.8.5 references exist",
        check_2_version_consistency,
    ),
    AuditCheck(
        3,
        "Numerical correctness tests exist",
        "Verify tests have assert_allclose calls (catches 'no tests' hallucinations)",
        check_3_numerical_tests_exist,
    ),
    AuditCheck(
        4,
        "Coverage threshold ≥ 10",
        "Verify CI coverage gate is reasonable (not 6%)",
        check_4_coverage_threshold,
    ),
    AuditCheck(
        5,
        "PyPI badges removed",
        "Verify README no longer links to fake PyPI badges",
        check_5_pypi_badges_redirected,
    ),
    AuditCheck(
        6,
        "Numerical tests pass",
        "Run tests/test_numerical_correctness.py and verify all pass",
        check_6_numerical_tests_pass,
    ),
    AuditCheck(
        7,
        "Demo outputs present (DISABLED — see check_7_demo_output_exists docstring)",
        "Disabled by user decision 2026-06-28 (audit_2026-06-28, Commit 0872901 删除了 demo_outputs/)",
        check_7_demo_output_exists,
    ),
    AuditCheck(
        8,
        "Cross-language validation present",
        "Verify R/Stata validation framework exists",
        check_8_validate_econometrics_exists,
    ),
    AuditCheck(
        9,
        "SSOT numbers match actual state",
        "Verify scripts/PROJECT_NUMBERS.json matches reality (root-cause fix for number hallucinations)",
        check_9_ssot_numbers_match_docs,
    ),
    AuditCheck(
        10,
        "LLMReviewer stable model",
        "Verify default judge_model is not gpt5 (non-existent)",
        check_10_llm_reviewer_stable_model,
    ),
    AuditCheck(
        11,
        "coverage omit size bounded",
        "Defense vs. audit-2026-07-04 P0-1 'omit to hide coverage' (cap=29)",
        check_11_omit_longtail_not_growing,
    ),
    AuditCheck(
        12,
        "CI fail-under floor",
        "Defense vs. audit-2026-07-04 P0-1 'lower threshold to pass' (floor=28 at PR-6; 60% deferred to PR-8)",
        check_12_fail_under_floor,
    ),
    AuditCheck(
        13,
        "Workflow YAML unquoted-colon check",
        "Defense: ci.yml YAML parse failures caused silent CI failures in PR-3 (a623563) and PR-4 (997abff). This check parses every .github/workflows/*.yml with PyYAML and flags any unquoted `name:` containing a colon.",
        check_13_workflow_yaml_unquoted_colons,
    ),
    AuditCheck(
        14,
        "diff-in-diff2 phantom dep",
        "Defense vs. phantom dep discovered by PR-4 test-full job: diff-in-diff2 does NOT exist on PyPI but was declared in requirements.txt and pyproject.toml. Code gracefully handles missing import via EstimatorUnavailableError.",
        check_14_diff_in_diff2_phantom_dep,
    ),
    AuditCheck(
        15,
        "PyPI deps existence (sample)",
        "Defense vs. typo'd / phantom deps: spot-checks first 30 deps from requirements.txt + pyproject.toml against PyPI. Skipped when network unavailable.",
        check_15_pypi_deps_exist,
    ),
    AuditCheck(
        16,
        "No hardcoded version drift",
        "Defense for 2026-07-11 audit: scan scripts/**/*.py for hardcoded 'vX.Y.Z' literals that drift from pyproject.toml [project].version",
        check_16_version_drift,
    ),
    AuditCheck(
        17,
        "No research integrity anti-patterns",
        "Defense for audit_fix_2026_07_12: detect (T001) mechanism tautology in us_esg_regression, "
        "(T002) RMSPE-ratio heuristic sig in synthetic_control, (T003) silent short-panel DID",
        check_17_no_research_integrity_anti_patterns,
    ),
    # T3 audit 2026-07-12: cross-platform reproducibility
    AuditCheck(
        18,
        "Cross-platform reproducibility layer exists",
        "Verify scripts/core/normalize.py exists with setup_reproducible_env + normalize_json_dumps + normalize_path",
        lambda: _check_reproducibility_layer(),
    ),
    # T4 audit 2026-07-12: MCP server registration health
    AuditCheck(
        19,
        "MCP server registration health",
        "Verify all mcp.json registered servers have working command + module path (excludes external whitelist)",
        lambda: _check_mcp_registration_health(),
    ),
    # T6 audit 2026-07-12: HITL (human-in-the-loop) coverage in research_framework pipeline
    AuditCheck(
        20,
        "HITL stage gates exist in research_framework pipeline",
        "Verify _hitl_pause() is called at data-loaded and regression-run stages, "
        "and that --no-hitl flag exists for batch CI runs",
        lambda: _check_hitl_coverage(),
    ),
    # T7 audit 2026-07-12: Health check skip flags exist
    AuditCheck(
        21,
        "Health check supports --ignore-data-source / --ignore-api-key",
        "Verify scripts/health_check.py main() exposes both flags so operators "
        "can suppress paid-MCP warnings when intentionally absent",
        lambda: _check_health_check_skip_flags(),
    ),
]  # noqa: E501


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Defensive guard against audit hallucinations"
    )
    parser.add_argument("--check", help="comma-separated check IDs (default: all)")
    parser.add_argument("--json", action="store_true", help="JSON output")
    parser.add_argument(
        "--update-baseline",
        action="store_true",
        help="Update expected state file (for legitimate baseline changes)",
    )
    args = parser.parse_args()

    if args.check:
        ids = {int(x) for x in args.check.split(",")}
        selected = [c for c in CHECKS if c.id in ids]
    else:
        selected = CHECKS

    results: list[tuple[AuditCheck, CheckResult]] = []
    for check in selected:
        print(f"\n[Check {check.id}] {check.title}")
        print(f"  {check.description}")
        try:
            result = check.run()
        except Exception as e:
            result = CheckResult(
                passed=False, actual=f"error: {e}", expected="verifiable", evidence=[str(e)]
            )
        status = "✓ PASS" if result.passed else "✗ FAIL"
        print(f"  {status}")
        print(f"  actual:   {result.actual}")
        print(f"  expected: {result.expected}")
        for ev in result.evidence:
            print(ev)
        results.append((check, result))

    # Summary
    passed = sum(1 for _, r in results if r.passed)
    total = len(results)

    if args.json:
        out = {
            "passed": passed,
            "total": total,
            "results": [
                {
                    "id": c.id,
                    "title": c.title,
                    "passed": r.passed,
                    "actual": r.actual,
                    "expected": r.expected,
                    "evidence": r.evidence,
                }
                for c, r in results
            ],
        }
        print("\n" + json.dumps(out, indent=2, ensure_ascii=False))
    else:
        print("\n" + "=" * 60)
        print(f"AUDIT GUARD: {passed}/{total} checks passed")
        print("=" * 60)

    return 0 if passed == total else 1


if __name__ == "__main__":
    sys.exit(main())
